version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis_db
    hostname: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    restart: always
    networks:
      - redis_net
  db:
    image: postgres:14.1-alpine
    restart: always
    expose:
      - 5433
    environment:
      - POSTGRES_USER=chaneto
      - POSTGRES_PASSWORD=12345
  api:
    container_name: game-container
    build:
      context: .
    image: game
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    command: --redis-host redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5433/games_db
      - SPRING_DATASOURCE_USERNAME=chaneto
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - WAIT_HOST=redis:6379
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - TZ=Europe/Sofia
    links:
      - redis:redis
      - db
    volumes:
      - './:/src'
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - redis_net
volumes:
  db:
    driver: local

networks:
  redis_net:
    driver: bridge
